#!/usr/bin/env python3
"""Fixed rust-fm-synthe id → strudel part/slug map. Source for slugs.toml."""

from __future__ import annotations

# (preset_id, part, slug, skip_copy, alias_or_empty)
# skip_copy: do not write WAV (bundled key already covers the role).
ENTRIES: list[tuple[str, str, str, bool, str]] = [
    # --- bd ---
    ("bd-808-boom", "bd", "8b", False, ""),
    ("bd-808-dist", "bd", "8d", False, ""),
    ("bd-808-tight", "bd", "8t", False, ""),
    ("bd-909-punch", "bd", "9p", False, ""),
    ("bd-cinematic", "bd", "cn", False, ""),
    ("bd-click", "bd", "ck", False, ""),
    ("bd-disco-dry", "bd", "dc", False, ""),
    ("bd-dnb-tight", "bd", "dn", False, ""),
    ("bd-electro-zap", "bd", "ez", False, ""),
    ("bd-fm-noise", "bd", "fn", False, ""),
    ("bd-frenchcore", "bd", "fc", False, ""),
    ("bd-gabber-stomp", "bd", "gb", False, ""),
    ("bd-hardstyle", "bd", "hs", False, ""),
    ("bd-house-floor", "bd", "hf", False, ""),
    ("bd-jungle-round", "bd", "jg", False, ""),
    ("bd-lofi-dust", "bd", "lf", False, ""),
    ("bd-metal-ping", "bd", "mt", False, ""),
    ("bd-neuro-growl", "bd", "ng", False, ""),
    ("bd-sub", "bd", "sb", False, ""),
    ("bd-techno-thud", "bd", "tc", False, ""),
    # --- sd ---
    ("sd-808-snap", "sd", "8s", False, ""),
    ("sd-909-snappy", "sd", "9s", False, ""),
    ("sd-brush-dust", "sd", "br", False, ""),
    ("sd-clap-snare", "sd", "cs", False, ""),
    ("sd-dnb-tight", "sd", "dn", False, ""),
    ("sd-fat-backbeat", "sd", "fb", False, ""),
    ("sd-fm-long", "sd", "fm", False, ""),
    ("sd-frenchcore", "sd", "fc", False, ""),
    ("sd-gabber-indust", "sd", "gb", False, ""),
    ("sd-gated-80s", "sd", "gt", False, ""),
    ("sd-house-disco", "sd", "hd", False, ""),
    ("sd-jungle-round", "sd", "jg", False, ""),
    ("sd-metal-ping", "sd", "mt", False, ""),
    ("sd-neuro-growl", "sd", "ng", False, ""),
    ("sd-noise-layer", "sd", "ns", False, ""),
    ("sd-piccolo", "sd", "pi", False, ""),
    ("sd-pop-tight", "sd", "pp", False, ""),
    ("sd-rimshot", "sd", "rm", False, ""),
    ("sd-tone-layer", "sd", "tn", False, ""),
    ("sd-trap-crisp", "sd", "tr", False, ""),
    # --- hh / oh / cp / tom from perc ---
    ("pc-hat-closed", "hh", "cl", False, ""),
    ("pc-hat-chip", "hh", "ch", False, ""),
    ("pc-hat-dark", "hh", "dk", False, ""),
    ("pc-hat-dnb-cl", "hh", "dn", False, ""),
    ("pc-hat-fc", "hh", "fc", False, ""),
    ("pc-hat-house", "hh", "hs", False, ""),
    ("pc-hat-noise", "hh", "ns", False, ""),
    ("pc-hat-pedal", "hh", "pd", False, ""),
    ("pc-hat-tight", "hh", "tt", False, ""),
    ("pc-hat-open", "oh", "op", False, ""),
    ("pc-hat-dnb-op", "oh", "dn", False, ""),
    ("pc-hat-fc-op", "oh", "fc", False, ""),
    ("pc-clap-dry", "cp", "dr", False, ""),
    ("pc-clap-gate", "cp", "gt", False, ""),
    ("pc-clap-room", "cp", "rm", False, ""),
    ("cp-house", "cp", "00", True, "cp"),
    ("pc-tom-hi", "tom", "hi", False, ""),
    ("pc-tom-lo", "tom", "lo", False, ""),
    ("pc-tom-mid", "tom", "md", False, ""),
    # --- perc remainder ---
    ("pc-agogo-hi", "perc", "ah", False, ""),
    ("pc-agogo-lo", "perc", "al", False, ""),
    ("pc-bongo-hi", "perc", "bh", False, ""),
    ("pc-bongo-lo", "perc", "bl", False, ""),
    ("pc-cabasa", "perc", "cb", False, ""),
    ("pc-chime", "perc", "cm", False, ""),
    ("pc-clave", "perc", "cv", False, ""),
    ("pc-conga-hi", "perc", "gh", False, ""),
    ("pc-conga-lo", "perc", "gl", False, ""),
    ("pc-cowbell", "perc", "cw", False, ""),
    ("pc-foley-click", "perc", "fk", False, ""),
    ("pc-foley-scratch", "perc", "fs", False, ""),
    ("pc-foley-thud", "perc", "ft", False, ""),
    ("pc-guiro", "perc", "gr", False, ""),
    ("pc-ride-bell", "perc", "rb", False, ""),
    ("pc-ride-fm", "perc", "rf", False, ""),
    ("pc-rim", "perc", "rm", False, ""),
    ("pc-shaker", "perc", "sk", False, ""),
    ("pc-shaker-short", "perc", "ss", False, ""),
    ("pc-snap", "perc", "sn", False, ""),
    ("pc-snap-lo", "perc", "sl", False, ""),
    ("pc-snaps", "perc", "np", False, ""),
    ("pc-stick", "perc", "st", False, ""),
    ("pc-tamb", "perc", "tb", False, ""),
    ("pc-tamb-roll", "perc", "tr", False, ""),
    ("pc-tick-clock", "perc", "tk", False, ""),
    ("pc-tick-indust", "perc", "ti", False, ""),
    ("pc-tick-metal", "perc", "tm", False, ""),
    ("pc-triangle", "perc", "tg", False, ""),
    ("pc-woodblock", "perc", "wb", False, ""),
    ("pc-zap", "perc", "zp", False, ""),
    ("pc-zap-lo", "perc", "zl", False, ""),
    ("glass-hit", "perc", "gs", False, ""),
    ("metallic-hit", "perc", "mh", False, ""),
    # --- bs ---
    ("bs-808-sub", "bs", "8s", False, ""),
    ("bs-acid", "bs", "ac", False, ""),
    ("bs-amen-sub", "bs", "am", False, ""),
    ("bs-dist-square", "bs", "dq", False, ""),
    ("bs-frenchcore", "bs", "fc", False, ""),
    ("bs-gabber", "bs", "gb", False, ""),
    ("bs-growl-2", "bs", "g2", False, ""),
    ("bs-hoover", "bs", "hv", False, ""),
    ("bs-house-tight", "bs", "ht", False, ""),
    ("bs-metal-fm", "bs", "mt", False, ""),
    ("bs-reese-bright", "bs", "rb", False, ""),
    ("bs-reese-dark", "bs", "rd", False, ""),
    ("bs-reese-neuro", "bs", "rn", False, ""),
    ("bs-sine-sub", "bs", "ss", False, ""),
    ("bs-wobble", "bs", "wb", False, ""),
    ("bp-growl", "bs", "bp", False, ""),
    ("growl-bass", "bs", "gr", False, ""),
    ("sub-bass", "bs", "sb", False, ""),
    ("supersaw-bass", "bs", "sw", False, ""),
    ("reese-mid", "bs", "rm", True, "bs:rm"),
    # --- ep ---
    ("ep-muted", "ep", "mt", False, ""),
    ("ep-rhodes-hard", "ep", "rh", False, ""),
    ("ep-rhodes-soft", "ep", "rs", False, ""),
    ("ep-tine-bell", "ep", "tb", False, ""),
    ("ep-wurli", "ep", "wr", False, ""),
    # --- plk ---
    ("pl-acid-short", "plk", "ac", False, ""),
    ("pl-ambient-soft", "plk", "am", False, ""),
    ("pl-arp-major", "plk", "aj", False, ""),
    ("pl-arp-minor", "plk", "an", False, ""),
    ("pl-bass-pluck", "plk", "bp", False, ""),
    ("pl-chime-high", "plk", "ch", False, ""),
    ("pl-clav-funk", "plk", "cv", False, ""),
    ("pl-dnb-neuro", "plk", "nn", False, ""),
    ("pl-dnb-tight", "plk", "dt", False, ""),
    ("pl-fm-crystal", "plk", "fc", False, ""),
    ("pl-fm-ep", "plk", "ep", False, ""),
    ("pl-future-glass", "plk", "fg", False, ""),
    ("pl-guitar-mute", "plk", "gm", False, ""),
    ("pl-harp-open", "plk", "hp", False, ""),
    ("pl-house-bright", "plk", "hb", False, ""),
    ("pl-house-dry", "plk", "hd", False, ""),
    ("pl-kalimba", "plk", "kl", False, ""),
    ("pl-koto", "plk", "kt", False, ""),
    ("pl-lofi-dust", "plk", "lf", False, ""),
    ("pl-mallet-bell", "plk", "mb", False, ""),
    ("pl-mallet-marimba", "plk", "mm", False, ""),
    ("pl-musicbox", "plk", "mx", False, ""),
    ("pl-perc-click", "plk", "pk", False, ""),
    ("pl-pop-nylon", "plk", "ny", False, ""),
    ("pl-pop-soft", "plk", "ps", False, ""),
    ("pl-reverse-swell", "plk", "rv", False, ""),
    ("pl-stab-fifth", "plk", "sf", False, ""),
    ("pl-stab-major", "plk", "sm", False, ""),
    ("pl-supersaw-short", "plk", "ss", False, ""),
    ("pl-trance-gate", "plk", "tg", False, ""),
    ("filter-pluck", "plk", "fp", False, ""),
    ("stab-pluck", "plk", "sp", False, ""),
    ("stab-fm-fifth", "plk", "s5", True, "plk:s5"),
    ("stab-fm-major", "plk", "s3", True, "plk:s3"),
    # --- fx ---
    ("fx-alarm", "fx", "al", False, ""),
    ("fx-blip", "fx", "bl", False, ""),
    ("fx-boom", "fx", "bm", False, ""),
    ("fx-clang", "fx", "cg", False, ""),
    ("fx-crackle", "fx", "ck", False, ""),
    ("fx-down-to-kick", "fx", "dk", False, ""),
    ("fx-downlifter", "fx", "dl", False, ""),
    ("fx-downlifter-noise", "fx", "dn", False, ""),
    ("fx-fall", "fx", "fl", False, ""),
    ("fx-formant-ah", "fx", "fa", False, ""),
    ("fx-formant-oh", "fx", "fo", False, ""),
    ("fx-frenchcore-ns", "fx", "fc", False, ""),
    ("fx-gabber-stab", "fx", "gb", False, ""),
    ("fx-glass-smash", "fx", "gs", False, ""),
    ("fx-hoover-fall", "fx", "hv", False, ""),
    ("fx-impact", "fx", "im", False, ""),
    ("fx-impact-dnb", "fx", "id", False, ""),
    ("fx-impact-mid", "fx", "md", False, ""),
    ("fx-laser", "fx", "lz", False, ""),
    ("fx-laser-fall", "fx", "lf", False, ""),
    ("fx-metal-crash", "fx", "mc", False, ""),
    ("fx-noise-burst", "fx", "nb", False, ""),
    ("fx-noise-hit", "fx", "nh", False, ""),
    ("fx-passby", "fx", "pb", False, ""),
    ("fx-radio-stab", "fx", "rd", False, ""),
    ("fx-rev-air", "fx", "ra", False, ""),
    ("fx-rev-crash", "fx", "rc", False, ""),
    ("fx-rev-crash-metal", "fx", "rm", False, ""),
    ("fx-rev-cym", "fx", "ry", False, ""),
    ("fx-rev-cym-bright", "fx", "rb", False, ""),
    ("fx-rev-cym-dark", "fx", "rk", False, ""),
    ("fx-rev-cym-long", "fx", "rl", False, ""),
    ("fx-rev-cym-noise", "fx", "rn", False, ""),
    ("fx-rev-hat", "fx", "rh", False, ""),
    ("fx-rev-splash", "fx", "rs", False, ""),
    ("fx-rev-verb", "fx", "rv", False, ""),
    ("fx-riser-filter", "fx", "rf", False, ""),
    ("fx-riser-noise", "fx", "nr", False, ""),
    ("fx-riser-pitch", "fx", "rp", False, ""),
    ("fx-riser-saw", "fx", "rw", False, ""),
    ("fx-siren", "fx", "sr", False, ""),
    ("fx-sub-drop", "fx", "sd", False, ""),
    ("fx-sweep-bp", "fx", "sw", False, ""),
    ("fx-tape-stop", "fx", "ts", False, ""),
    ("fx-trans-fill", "fx", "tf", False, ""),
    ("fx-uplifter", "fx", "up", False, ""),
    ("fx-whoosh", "fx", "wh", False, ""),
    ("fx-whoosh-hp", "fx", "wp", False, ""),
    ("fx-wind", "fx", "wd", False, ""),
    ("fx-zap", "fx", "zp", False, ""),
    ("fm-riser", "fx", "fr", False, ""),
    ("hp-air", "fx", "ha", False, ""),
    ("zap", "fx", "zz", False, ""),
    # --- ld (long; default import skips this part) ---
    ("ld-acid", "ld", "ac", False, ""),
    ("ld-anthem", "ld", "an", False, ""),
    ("ld-arp-pluck", "ld", "ap", False, ""),
    ("ld-bell-pluck", "ld", "bl", False, ""),
    ("ld-brass", "ld", "br", False, ""),
    ("ld-chip", "ld", "ch", False, ""),
    ("ld-choir", "ld", "cr", False, ""),
    ("ld-cinematic", "ld", "cn", False, ""),
    ("ld-crystal", "ld", "cy", False, ""),
    ("ld-dist-pulse", "ld", "dp", False, ""),
    ("ld-dnb-stab", "ld", "ds", False, ""),
    ("ld-drop-pluck", "ld", "dr", False, ""),
    ("ld-ethereal", "ld", "et", False, ""),
    ("ld-fifth-pad", "ld", "fp", False, ""),
    ("ld-flute", "ld", "fl", False, ""),
    ("ld-fm-pluck", "ld", "fm", False, ""),
    ("ld-formant", "ld", "fo", False, ""),
    ("ld-frenchcore", "ld", "fc", False, ""),
    ("ld-gabber", "ld", "gb", False, ""),
    ("ld-glass", "ld", "gl", False, ""),
    ("ld-growl", "ld", "gr", False, ""),
    ("ld-half-sine", "ld", "hs", False, ""),
    ("ld-hardstyle", "ld", "hd", False, ""),
    ("ld-harpsi", "ld", "hp", False, ""),
    ("ld-hollow-fifth", "ld", "hf", False, ""),
    ("ld-hoover", "ld", "hv", False, ""),
    ("ld-house-pluck", "ld", "hu", False, ""),
    ("ld-industrial", "ld", "in", False, ""),
    ("ld-laser", "ld", "lz", False, ""),
    ("ld-mallet", "ld", "ml", False, ""),
    ("ld-metallic", "ld", "mt", False, ""),
    ("ld-music-box", "ld", "mx", False, ""),
    ("ld-noisy-bp", "ld", "nb", False, ""),
    ("ld-nylon", "ld", "ny", False, ""),
    ("ld-octave", "ld", "oc", False, ""),
    ("ld-organ", "ld", "or", False, ""),
    ("ld-perc", "ld", "pc", False, ""),
    ("ld-pulse", "ld", "pu", False, ""),
    ("ld-reed", "ld", "rd", False, ""),
    ("ld-reverse", "ld", "rv", False, ""),
    ("ld-saw-pluck", "ld", "sw", False, ""),
    ("ld-sine", "ld", "si", False, ""),
    ("ld-supersaw", "ld", "ss", False, ""),
    ("ld-supersaw-stab", "ld", "st", False, ""),
    ("ld-sync-fm", "ld", "sf", False, ""),
    ("ld-trance-gate", "ld", "tg", False, ""),
    ("ld-unison-saw", "ld", "us", False, ""),
    ("ld-vowel", "ld", "vw", False, ""),
    ("ld-wobble", "ld", "wb", False, ""),
    ("ld-zap", "ld", "zp", False, ""),
    ("lead-fm-pluck", "ld", "lp", True, "plk:lp"),
    # --- dr ---
    ("dr-abyss", "dr", "ab", False, ""),
    ("dr-ambient-dark", "dr", "ad", False, ""),
    ("dr-brass-distant", "dr", "bd", False, ""),
    ("dr-brass-pad", "dr", "bp", False, ""),
    ("dr-cathedral", "dr", "ct", False, ""),
    ("dr-choir-dark", "dr", "cd", False, ""),
    ("dr-choir-low", "dr", "cl", False, ""),
    ("dr-dystopia", "dr", "dy", False, ""),
    ("dr-engine", "dr", "en", False, ""),
    ("dr-fifth-hollow", "dr", "fh", False, ""),
    ("dr-fm-bell-low", "dr", "fb", False, ""),
    ("dr-fm-evolve", "dr", "fe", False, ""),
    ("dr-fm-index", "dr", "fi", False, ""),
    ("dr-fog", "dr", "fg", False, ""),
    ("dr-formant-low", "dr", "fl", False, ""),
    ("dr-ghost-choir", "dr", "gc", False, ""),
    ("dr-horror", "dr", "hr", False, ""),
    ("dr-hum-grid", "dr", "hg", False, ""),
    ("dr-ice-cave", "dr", "ic", False, ""),
    ("dr-impact-hold", "dr", "ih", False, ""),
    ("dr-industrial", "dr", "id", False, ""),
    ("dr-metal-bed", "dr", "mb", False, ""),
    ("dr-metal-distant", "dr", "md", False, ""),
    ("dr-minor-dark", "dr", "mn", False, ""),
    ("dr-noisy-bp", "dr", "nb", False, ""),
    ("dr-octave-stack", "dr", "os", False, ""),
    ("dr-pad-dark", "dr", "pd", False, ""),
    ("dr-pulse-fifth", "dr", "pf", False, ""),
    ("dr-pulse-rumble", "dr", "pr", False, ""),
    ("dr-reactor", "dr", "rc", False, ""),
    ("dr-reese-dark", "dr", "rd", False, ""),
    ("dr-reese-wide", "dr", "rw", False, ""),
    ("dr-reverse-hold", "dr", "rh", False, ""),
    ("dr-riser-slow", "dr", "rs", False, ""),
    ("dr-ritual", "dr", "ri", False, ""),
    ("dr-rumble", "dr", "rm", False, ""),
    ("dr-saw-minor", "dr", "sm", False, ""),
    ("dr-scifi-hum", "dr", "sh", False, ""),
    ("dr-score-hold", "dr", "sc", False, ""),
    ("dr-sine-sub", "dr", "ss", False, ""),
    ("dr-storm", "dr", "st", False, ""),
    ("dr-sub-octave", "dr", "so", False, ""),
    ("dr-supersaw-low", "dr", "sl", False, ""),
    ("dr-tape-hum", "dr", "th", False, ""),
    ("dr-thunder-bed", "dr", "tb", False, ""),
    ("dr-trailer-bloom", "dr", "tl", False, ""),
    ("dr-underwater", "dr", "uw", False, ""),
    ("dr-void", "dr", "vd", False, ""),
    ("dr-warfare", "dr", "wf", False, ""),
    ("dr-wobble-slow", "dr", "ws", False, ""),
    # --- pf ---
    ("pf-alpine", "pf", "al", False, ""),
    ("pf-breeze", "pf", "br", False, ""),
    ("pf-choir-air", "pf", "ca", False, ""),
    ("pf-chorus-wide", "pf", "cw", False, ""),
    ("pf-clear-saw", "pf", "cs", False, ""),
    ("pf-cloud", "pf", "cl", False, ""),
    ("pf-dawn", "pf", "dn", False, ""),
    ("pf-fifth-open", "pf", "fo", False, ""),
    ("pf-flute-pad", "pf", "fl", False, ""),
    ("pf-glass-air", "pf", "ga", False, ""),
    ("pf-halo", "pf", "hl", False, ""),
    ("pf-harp-air", "pf", "ha", False, ""),
    ("pf-horizon", "pf", "hz", False, ""),
    ("pf-ivory", "pf", "iv", False, ""),
    ("pf-juno-air", "pf", "ju", False, ""),
    ("pf-linen", "pf", "ln", False, ""),
    ("pf-lydian-sky", "pf", "ly", False, ""),
    ("pf-major-soft", "pf", "ms", False, ""),
    ("pf-meadow", "pf", "md", False, ""),
    ("pf-morning", "pf", "mn", False, ""),
    ("pf-ninth-open", "pf", "ni", False, ""),
    ("pf-octave-light", "pf", "oc", False, ""),
    ("pf-organ-light", "pf", "or", False, ""),
    ("pf-pulse-air", "pf", "pu", False, ""),
    ("pf-reed-soft", "pf", "rs", False, ""),
    ("pf-silk", "pf", "sk", False, ""),
    ("pf-sky-open", "pf", "so", False, ""),
    ("pf-spring", "pf", "sp", False, ""),
    ("pf-water-air", "pf", "wa", False, ""),
    ("pf-wide-major", "pf", "wm", False, ""),
    # --- ps ---
    ("ps-aurora", "ps", "au", False, ""),
    ("ps-bell-air", "ps", "ba", False, ""),
    ("ps-bell-hold", "ps", "bh", False, ""),
    ("ps-celesta", "ps", "ce", False, ""),
    ("ps-celestial", "ps", "cs", False, ""),
    ("ps-chime-pad", "ps", "cp", False, ""),
    ("ps-chorus-shine", "ps", "ch", False, ""),
    ("ps-crystal", "ps", "cr", False, ""),
    ("ps-crystal-choir", "ps", "cc", False, ""),
    ("ps-diamond", "ps", "dm", False, ""),
    ("ps-fm-sparkle", "ps", "fs", False, ""),
    ("ps-frost", "ps", "fr", False, ""),
    ("ps-glass-bell", "ps", "gb", False, ""),
    ("ps-glisten", "ps", "gl", False, ""),
    ("ps-glitter", "ps", "gt", False, ""),
    ("ps-glock-pad", "ps", "gp", False, ""),
    ("ps-halo-shine", "ps", "hs", False, ""),
    ("ps-high-partials", "ps", "hp", False, ""),
    ("ps-ice-choir", "ps", "ic", False, ""),
    ("ps-ice-shine", "ps", "is", False, ""),
    ("ps-inharmonic", "ps", "ih", False, ""),
    ("ps-music-box", "ps", "mx", False, ""),
    ("ps-prism", "ps", "pr", False, ""),
    ("ps-quartz", "ps", "qz", False, ""),
    ("ps-shimmer", "ps", "sh", False, ""),
    ("ps-shine-fifth", "ps", "sf", False, ""),
    ("ps-silver", "ps", "sv", False, ""),
    ("ps-spark-evolve", "ps", "se", False, ""),
    ("ps-starlight", "ps", "sl", False, ""),
    ("ps-twinkle", "ps", "tw", False, ""),
]

DEFAULT_PARTS = {
    "bd",
    "sd",
    "hh",
    "oh",
    "cp",
    "tom",
    "perc",
    "bs",
    "plk",
    "ep",
    "fx",
}

LONG_PARTS = {"ld", "dr", "pf", "ps"}

# Existing repo flats (`samples/<old>.wav`) moved onto part:slug.
# overwrite=True replaces a catalog file at the same dest (keep the signed-off 48 kHz render).
# (old_stem, part, slug, overwrite, name, description)
BUNDLED_FLATS: list[tuple[str, str, str, bool, str, str]] = [
    (
        "bass-fm_house",
        "bs",
        "hf",
        False,
        "house floor bass",
        "C2 tight house floor (batch 1). Native C2; write C4:…. Pairs with bd:hf.",
    ),
    (
        "bass-fm_sub",
        "bs",
        "su",
        False,
        "fm sine sub",
        "C2 clean sine sub (batch 1). Floor only. Write C4:…. Do not stack with other subs.",
    ),
    (
        "fx-impact_dnb",
        "fx",
        "id",
        True,
        "DnB impact",
        "Unpitched DnB impact (~0.5 s). Bare s(); no note().",
    ),
    (
        "fx-riser_noise",
        "fx",
        "nr",
        True,
        "noise riser",
        "Unpitched noise riser (~3.2 s). Use <> so it is not every bar.",
    ),
    (
        "fx-sub_drop",
        "fx",
        "sd",
        True,
        "sub drop",
        "Unpitched sub drop (~1.1 s). Kick lead-in, not a bass note.",
    ),
    (
        "fx-uplifter",
        "fx",
        "up",
        True,
        "uplifter",
        "Unpitched uplifter (~2.8 s). s(\"<fx:up ~ ~ ~>\") once per 4 bars.",
    ),
    (
        "keys-fm_ep",
        "ep",
        "ky",
        False,
        "FM EP one-shot",
        "C3 EP tines (2×/3×). Write C4:…. Not the live 2-op lead.",
    ),
    (
        "lead-fm_bell",
        "plk",
        "bl",
        False,
        "FM bell pluck",
        "C3 inharmonic bell / glass (ratio 3.5). Write C4:…. Not a pad.",
    ),
    (
        "lead-fm_pluck",
        "plk",
        "lp",
        False,
        "FM pluck",
        "C3 short FM pluck. Write C4:…. .cut(1) if monophonic.",
    ),
    (
        "lead-supersaw",
        "ld",
        "ss",
        True,
        "supersaw lead",
        "C3 classic supersaw hold (~8 s). Write C4:…. .cut(1) for melody.",
    ),
    (
        "pad-fm_fifth",
        "pf",
        "ff",
        False,
        "fifth pad",
        "C3 hollow C+G pad (~8 s). Write C4:…. Cannot invent a third.",
    ),
    (
        "perc-fm_metal",
        "perc",
        "fm",
        False,
        "FM metal hit",
        "Unpitched metallic hit. Not a stab or kick.",
    ),
    (
        "reese-dark",
        "bs",
        "dk",
        False,
        "dark Reese",
        "C3 full-range dark Reese with sub. Write C4:…. Do not stack with other subs.",
    ),
    (
        "reese-mid",
        "bs",
        "rm",
        False,
        "mid Reese glue",
        "C3 800–1200 Hz glue, no sub. Write C4:…. Needs a separate sub.",
    ),
    (
        "stab-fm_fifth",
        "plk",
        "s5",
        False,
        "hollow fifth stab",
        "C3 C+G only (no third). Write C4:…. Sparse degrees.",
    ),
    (
        "stab-fm_major",
        "plk",
        "s3",
        False,
        "major triad stab",
        "C3 C–E–G already in the wav. note(\"0 ~ 0 ~\") only — do not [0,2,4].",
    ),
]


def by_id() -> dict[str, tuple[str, str, bool, str]]:
    return {i: (p, s, skip, alias) for i, p, s, skip, alias in ENTRIES}


def validate() -> list[str]:
    errors: list[str] = []
    seen_ids: set[str] = set()
    per_part: dict[str, set[str]] = {}
    for pid, part, slug, skip, alias in ENTRIES:
        if pid in seen_ids:
            errors.append(f"duplicate id {pid}")
        seen_ids.add(pid)
        if skip:
            continue
        if slug.isdigit():
            errors.append(f"{pid}: slug {slug!r} is pure digits")
        if not (2 <= len(slug) <= 4):
            errors.append(f"{pid}: slug {slug!r} length")
        if not slug.replace("2", "x").replace("3", "x").replace("5", "x").replace("8", "x").replace("9", "x").isalnum():
            # allow digits in mnemonic; still must be [a-z0-9]
            if not all(c.isalnum() for c in slug):
                errors.append(f"{pid}: slug {slug!r} not alnum")
        bag = per_part.setdefault(part, set())
        if slug in bag:
            errors.append(f"duplicate {part}:{slug} ({pid})")
        bag.add(slug)
        if alias and not skip:
            errors.append(f"{pid}: alias without skip")
    copied = {(p, s) for i, p, s, skip, a in ENTRIES if not skip}
    seen_b: dict[str, set[str]] = {}
    for old, part, slug, overwrite, _n, _d in BUNDLED_FLATS:
        if slug.isdigit() or not (2 <= len(slug) <= 4):
            errors.append(f"bundled {old}: bad slug {slug!r}")
        bag = seen_b.setdefault(part, set())
        if slug in bag:
            errors.append(f"bundled duplicate {part}:{slug}")
        bag.add(slug)
        if overwrite and (part, slug) not in copied:
            errors.append(f"bundled {old} overwrite {part}:{slug} but no catalog dest")
        if not overwrite and (part, slug) in copied:
            errors.append(f"bundled {old} collides with catalog {part}:{slug}")
    return errors


def emit_toml() -> str:
    lines = [
        "# rust-fm-synthe preset id → strudel part + 2–3 char slug.",
        "# Unique per part. skip=true means do not copy WAV (use alias key instead).",
        "# Generated from scripts/fm_pcm_slugs.py — edit that file and re-run emit.",
        "",
        "[e]",
    ]
    for pid, part, slug, skip, alias in ENTRIES:
        bits = [f'part = "{part}"', f'slug = "{slug}"']
        if skip:
            bits.append("skip = true")
        if alias:
            bits.append(f'alias = "{alias}"')
        lines.append(f'"{pid}" = {{ {", ".join(bits)} }}')
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    err = validate()
    if err:
        raise SystemExit("\n".join(err))
    print(f"ok {len(ENTRIES)} entries")
